name: release

on:
  push:
    tags:
      - v*.*.*
  workflow_dispatch:

env:
  RUST_TOOLCHAIN_VERSION: nightly

jobs:
  build:
    name: Build 
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/cache@v2
        id: toolchain
        with:
          path: |
            ~/.cargo/bin/
          key: ${{ runner.os }}-cargo-${{ env.RUST_TOOLCHAIN_VERSION }}
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-deps-${{ hashFiles('**/Cargo.toml') }}

      - uses: actions-rs/toolchain@v1.0.6
        if: steps.toolchain.outputs.cache-hit != 'true'
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN_VERSION }}
          override: true

      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'npm'
          cache-dependency-path: 'www/package-lock.json'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set version
        run: |
          echo VERSION=${GITHUB_REF/refs\/tags\/v/} >> $GITHUB_ENV
          echo GIT_SHA=$GITHUB_SHA >> $GITHUB_ENV
          echo GIT_LINK=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/commit/$GITHUB_SHA >> $GITHUB_ENV

      - name: Setup wasm-pack
        run: 'curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh'

      - name: Build padme-wasm
        run: 'wasm-pack build --features console_error_panic_hook --features --features console_log'

      - name: Install www deps
        run: npm install
        working-directory: ./www

      - name: Build www
        run: npm run build
        working-directory: ./www
        env:
          NODE_ENV: production

      - name: Publish
        run: 'aws s3 sync --delete www/build s3://${S3_ENDPOINT}'
        env:
          S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
