name: release

on:
  push:
    tags:
      - v*.*.*
  workflow_dispatch:

env:
  RUST_TOOLCHAIN_VERSION: nightly-2022-04-15

jobs:
  build:
    name: Build 
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/cache@v2
        id: toolchain
        with:
          path: |
            ~/.cargo/bin/
          key: ${{ runner.os }}-cargo-${{ env.RUST_TOOLCHAIN_VERSION }}
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-deps-${{ hashFiles('**/Cargo.toml') }}

      - uses: actions-rs/toolchain@v1.0.6
        if: steps.toolchain.outputs.cache-hit != 'true'
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN_VERSION }}
          override: true

      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'npm'
          cache-dependency-path: 'www/package-lock.json'

      - name: Set version
        run: |
          echo VERSION=${GITHUB_REF/refs\/tags\/v/} >> $GITHUB_ENV
          echo GIT_SHA=${GITHUB_SHA:0:8} >> $GITHUB_ENV
          echo GIT_LINK=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/tree/$GITHUB_SHA >> $GITHUB_ENV
          echo PUBLIC_URL=https://padme.cc >> $GITHUB_ENV

      - name: Setup wasm-pack
        run: 'curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh'

      - name: Build padme-wasm
        run: 'wasm-pack build --features console_error_panic_hook --features --features console_log'

      - name: Install www deps
        run: npm install
        working-directory: ./www

      - name: Build www
        run: npm run build
        working-directory: ./www
        env:
          NODE_ENV: production

      - uses: actions/checkout@v3
        with:
          repository: ${{ secrets.SITE_REPO }}
          token: ${{ secrets.GHA_PADME_CC_TOKEN }}
          path: padme.cc

      - name: Update page
        run: |
          rm -rf ./*
          echo "# [$VERSION]($GIT_LINK)" > README.md
          cp -r ../www/build/* .
          git config --local user.email "ig11@bots.noreply.github.com"
          git config --local user.name "IG-11"
          git add .
          git commit -m "v$VERSION"
        working-directory: ./padme.cc

      - name: Deploy
        uses: ad-m/github-push-action@master
        with:
          github_token:  ${{ secrets.GHA_PADME_CC_TOKEN }}
          branch: main
          directory: ./padme.cc
          repository: ${{ secrets.SITE_REPO }}
